import { useEffect } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import BackToTop from '@/components/BackToTop';
import { Button } from '@/components/ui/button';

export default function BlogPost() {
  // Load Material Icons from Google CDN
  useEffect(() => {
    const link = document.createElement('link');
    link.href = 'https://fonts.googleapis.com/icon?family=Material+Icons';
    link.rel = 'stylesheet';
    document.head.appendChild(link);

    // Load Google Fonts: Baloo 2 and Nunito Sans
    const fontLink = document.createElement('link');
    fontLink.href = 'https://fonts.googleapis.com/css2?family=Baloo+2:wght@500;700&family=Nunito+Sans:wght@400;600;700&display=swap';
    fontLink.rel = 'stylesheet';
    document.head.appendChild(fontLink);

    return () => {
      document.head.removeChild(link);
      document.head.removeChild(fontLink);
    };
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-gray-50 font-['Nunito_Sans'] text-[#0A3A68]">
      <Header />

      <main className="max-w-5xl mx-auto px-4 py-6 md:py-10 flex-grow">
        <section className="bg-white shadow rounded-xl p-6 mb-10">
          <h1 className="text-3xl md:text-4xl font-['Baloo_2'] font-bold text-[#FF4C00] mb-4">
            Styling-Optionen für deinen Blogbeitrag
          </h1>
          <p className="text-base md:text-lg mb-4">
            Ein ansprechender Blogbeitrag lebt von guter Formatierung. In diesem Beispielartikel zeigen wir dir verschiedene Styling-Optionen, die du in deinen eigenen Beiträgen verwenden kannst.
          </p>
          <p className="text-lg italic text-gray-600 border-l-4 border-[#00CFFF] pl-4 py-2 mb-6">
            "Ein gutes Design ist nicht nur das, was man sieht, sondern auch, wie es funktioniert." - Steve Jobs
          </p>

          <h2 className="text-2xl font-['Baloo_2'] font-bold text-[#FF4C00] border-b-2 border-[#00CFFF]/50 pb-2 mb-4">
            Überschriften
          </h2>
          <div className="space-y-4 mb-6">
            <div className="p-4 bg-gray-50 rounded-md">
              <h2 className="text-2xl font-['Baloo_2'] font-bold text-[#FF4C00]">Überschrift Stufe 2</h2>
              <p className="text-sm text-gray-500">Wird verwendet für Hauptabschnitte</p>
            </div>
            <div className="p-4 bg-gray-50 rounded-md">
              <h3 className="text-xl font-['Baloo_2'] font-bold text-[#0A3A68]">Überschrift Stufe 3</h3>
              <p className="text-sm text-gray-500">Für Unterabschnitte</p>
            </div>
          </div>

          <h2 className="text-2xl font-['Baloo_2'] font-bold text-[#FF4C00] border-b-2 border-[#00CFFF]/50 pb-2 mb-4">
            Zitate
          </h2>
          <blockquote className="border-l-4 border-[#0A3A68] pl-4 py-2 italic text-gray-700 mb-4">
            "Das Geheimnis des Erfolgs ist anzufangen."
            <footer className="mt-2 text-sm text-[#0A3A68] not-italic">— Mark Twain</footer>
          </blockquote>

          <h2 className="text-2xl font-['Baloo_2'] font-bold text-[#FF4C00] border-b-2 border-[#00CFFF]/50 pb-2 mb-4">
            Tabellen
          </h2>
          <div className="overflow-x-auto bg-gray-50 p-4 rounded-md mb-6">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-[#0A3A68] text-white">
                  <th className="border border-gray-300 px-4 py-2 text-left">Produkt</th>
                  <th className="border border-gray-300 px-4 py-2 text-left">Beschreibung</th>
                  <th className="border border-gray-300 px-4 py-2 text-right">Preis</th>
                </tr>
              </thead>
              <tbody>
                <tr className="bg-white">
                  <td className="border border-gray-300 px-4 py-2 font-medium">Würfelboost S</td>
                  <td className="border border-gray-300 px-4 py-2">25.000 Würfel</td>
                  <td className="border border-gray-300 px-4 py-2 text-right">25 €</td>
                </tr>
                <tr className="bg-gray-50">
                  <td className="border border-gray-300 px-4 py-2 font-medium">Würfelboost M</td>
                  <td className="border border-gray-300 px-4 py-2">35.000 Würfel</td>
                  <td className="border border-gray-300 px-4 py-2 text-right">35 €</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h2 className="text-2xl font-['Baloo_2'] font-bold text-[#FF4C00] border-b-2 border-[#00CFFF]/50 pb-2 mb-4">
            Code-Beispiel
          </h2>
          <pre className="bg-gray-800 text-white p-4 rounded-md overflow-x-auto text-sm mb-6">
            <code>{`// Beispiel: JS-Funktion
function sendMessage() {
  const name = document.getElementById('name').value;
  const message = document.getElementById('message').value;

  if (!name || !message) {
    alert('Bitte fülle alle Felder aus!');
    return;
  }

  console.log('Nachricht gesendet:', { name, message });
}`}</code>
          </pre>
        </section>
              {/* Rest of the content */}
              
            
        
              
      
              
      
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
      
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
              
      
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
              
        
</section>
      </main>

      <BackToTop />
      <Footer />
    </div>
  );
}